# Generated by Django 5.2.7 on 2025-10-28 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('max_conversations', models.PositiveIntegerField(default=1000)),
                ('max_voice_minutes', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('moderator', 'Moderator')], default='super_admin', max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='admin_avatars/')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('can_manage_clients', models.BooleanField(default=True)),
                ('can_manage_intents', models.BooleanField(default=True)),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('can_handle_escalations', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('ai_audio_response_url', models.URLField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transcription', models.TextField(blank=True)),
                ('ai_text_response', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('language_detected', models.CharField(default='bn', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='core.client')),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BanglaConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('satisfaction_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('is_escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('escalated', 'Escalated to Human'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('human_response', models.TextField(blank=True)),
                ('human_responded_at', models.DateTimeField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('intent_detected', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.client')),
            ],
            options={
                'verbose_name': 'Bangla Conversation',
                'verbose_name_plural': 'Bangla Conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BanglaIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('training_phrase', models.TextField()),
                ('ai_response_template', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('examples', models.JSONField(default=list, help_text='List of training examples')),
                ('responses', models.JSONField(default=list, help_text='List of possible responses')),
                ('confidence_threshold', models.FloatField(default=0.8)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='core.client')),
            ],
            options={
                'verbose_name': 'Bangla Intent',
                'verbose_name_plural': 'Bangla Intents',
                'ordering': ['name'],
                'unique_together': {('client', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('date', models.DateField()),
                ('total_chats', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('failed_queries', models.PositiveIntegerField(default=0)),
                ('escalated_chats', models.PositiveIntegerField(default=0)),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('total_call_duration', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.client')),
            ],
            options={
                'verbose_name': 'Analytics',
                'verbose_name_plural': 'Analytics',
                'ordering': ['-date'],
                'unique_together': {('client', 'period', 'date')},
            },
        ),
    ]
