# Generated by Django 5.2.7 on 2025-10-25 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechSynthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_type', models.CharField(default='neutral', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('speed', models.FloatField(default=1.0)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='synthesized_speech/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speech_synthesis', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_syntheses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speech Synthesis',
                'verbose_name_plural': 'Speech Syntheses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_recordings/')),
                ('file_format', models.CharField(choices=[('wav', 'WAV'), ('mp3', 'MP3'), ('ogg', 'OGG'), ('webm', 'WebM'), ('m4a', 'M4A')], max_length=10)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField()),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('transcription', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('detected_language', models.CharField(blank=True, max_length=10)),
                ('language_confidence', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Recording',
                'verbose_name_plural': 'Voice Recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('interrupted', 'Interrupted'), ('failed', 'Failed')], default='active', max_length=20)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('voice_type', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('neutral', 'Neutral'), ('young', 'Young'), ('old', 'Old')], default='neutral', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('speed', models.FloatField(default=1.0)),
                ('total_recordings', models.PositiveIntegerField(default=0)),
                ('total_duration', models.DurationField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_session', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Session',
                'verbose_name_plural': 'Voice Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('total_voice_sessions', models.PositiveIntegerField(default=0)),
                ('total_recordings', models.PositiveIntegerField(default=0)),
                ('total_speech_syntheses', models.PositiveIntegerField(default=0)),
                ('average_transcription_confidence', models.FloatField(default=0.0)),
                ('average_language_detection_confidence', models.FloatField(default=0.0)),
                ('total_audio_duration', models.DurationField(default=0)),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('failed_transcriptions', models.PositiveIntegerField(default=0)),
                ('failed_syntheses', models.PositiveIntegerField(default=0)),
                ('language_distribution', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_analytics', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Voice Analytics',
                'verbose_name_plural': 'Voice Analytics',
                'ordering': ['-date'],
                'unique_together': {('organization', 'date', 'period')},
            },
        ),
    ]
