# Generated by Django 5.2.7 on 2025-10-30 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceanalytics',
            name='total_audio_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='voicesession',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
